name: Github Actions for building and pushing docker

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout front-end and backend
      - uses: actions/checkout@v4
