name: Github Actions for building and pushing docker

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push Docker image for Backend
        working-directory: ./backend
        run: |
          cat Dockerfile