name: Github Actions for building and pushing docker

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push Docker image for Backend
        working-directory: ./backend
        run: |
          sed -i '/PORT=/c\PORT=${{ secrets.MONGO_PORT }}' .env
          sed -i '/MONGO_USER=/c\MONGO_USER=${{ secrets.MONGO_USER }}' .env
          sed -i '/MONGO_PASS=/c\MONGO_PASS=${{ secrets.MONGO_PASS }}' .env
          sed -i '/MONGO_API=/c\MONGO_API=${{ secrets.MONGO_API }}' .env
          cat .env